[project]
name = "hexlet-code"
version = "0.1.0"
description = "Task manager"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.7",
]

[dependency-groups]
dev = [
    "ruff>=0.13.3",
]
