line-length = 80

[lint.per-file-ignores]
  # init modules can contain the local imports, logic, unused imports
"__init__.py" = ["F401"]
"settings.py" = ["E", "F", "I", "C90"]
"migrations/*" = ["E", "F", "I", "C90"]

[lint]
preview = true
select = ["E", "F", "I", "C90"]
