# Generated by Django 5.2.7 on 2025-10-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(help_text='lalala', max_length=200),
        ),
    ]
