# Generated by Django 5.2.7 on 2025-10-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(default=None, help_text='Ваш пароль должен содержать как минимум 3 символа.', max_length=200, verbose_name='Пароль'),
        ),
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(default=None, help_text='Для подтверждения введите, пожалуйста, пароль ещё раз.', max_length=200, verbose_name='Подтверждение пароля'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(help_text='Обязательное поле. Не более 150 символов. Только буквы, цифры и символы @/./+/-/_.', max_length=200, verbose_name='Имя пользователя'),
        ),
    ]
