# Generated by Django 5.2.7 on 2025-10-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_password1_user_password2_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password1',
            field=models.CharField(default='password', help_text='Ваш пароль должен содержать как минимум 3 символа.', max_length=200, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password2',
            field=models.CharField(default='password', help_text='Для подтверждения введите, пожалуйста, пароль ещё раз.', max_length=200, verbose_name='Подтверждение пароля'),
        ),
    ]
