# Generated by Django 5.2.7 on 2025-10-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_password1_alter_user_password2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password1',
            field=models.CharField(help_text='Ваш пароль должен содержать как минимум 3 символа.', max_length=200, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password2',
            field=models.CharField(help_text='Для подтверждения введите, пожалуйста, пароль ещё раз.', max_length=200, verbose_name='Подтверждение пароля'),
        ),
    ]
