# Generated by Django 5.2.7 on 2025-11-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='default', max_length=300, verbose_name='Полное имя'),
        ),
    ]
