# Generated by Django 5.2.7 on 2025-11-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=300, verbose_name='Полное имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Имя пользователя должно быть уникальным.'}, help_text='Обязательное поле. Не более 150 символов.             Только буквы, цифры и символы @/./+/-/_.', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
