# Generated by Django 5.2.7 on 2025-11-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя'),
        ),
    ]
